cc_binary(
    name = 'greeter_server',
    srcs = ['greeter_server.cc'],
    deps = [
        '//proto:helloworld_proto',
    ],
)

cc_binary(
    name = 'greeter_client',
    srcs = ['greeter_client.cc'],
    deps = [
        '//proto:helloworld_proto',
    ],
)