cc_test(
    name = "abseil_demo",
    srcs = [
        "abseil_demo.cc",
    ],
    deps = [
        "@com_google_absl//absl/strings:strings",
    ],
    copts = [
    	    "-pthread",
    ],
    linkopts = [
        "-pthread",
    ],
)
